# Generated by Django 5.0.4 on 2024-04-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_manufactured_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'ContactsView',
                'verbose_name_plural': 'ContactsViews',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufactured_at',
        ),
    ]
